# Site settings
title: Systers
email: systers-keeper@systers.org
url: https://systers.org
description: "Systers provides a private, safe online forum for women involved in technical aspects of computing. Our members gain support by networking, sharing advice and experiences, and collaborating on various projects. We welcome women of all ages and at any stage of their studies or careers."
keywords: "women, tech, diversity, women in tech, diversity in tech, networking"
meta_author: Systers
text: "A community by women in tech for women in tech"
logo: img/logo.png
showAffinityGroupPortfolio: false

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ef4135 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  button-color: 52b9e9

# Footer settings
footer:
  copyright: Systers
  keepers: Systers Keepers
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/systers_org
  - title: facebook
    url:
  - title: github
    url: https://github.com/anitab-org

# Systers Keepers
keepers:
  - line: Zaza
  - line: Megan
  - line: Prachi
  - line: Jennifer

# Credits content
credits: 'The systers community is a part of <a href="https://anitab.org/">AnitaB.org</a>. The website design was inspired by and based on <a href="https://github.com/jeromelachaud/freelancer-theme">Freelance Bootstrap Theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
      